

package enterprise.pro;

import java.awt.Toolkit;
import java.awt.geom.RoundRectangle2D;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.ResultSet; 
import javax.swing.JFrame;
import javax.swing.JOptionPane;
/**
 *
 * @author pplch
 */
public class loginPage extends javax.swing.JFrame {

    /**
     * Creates new form loginPage
     */
    public loginPage() {
         //icon changing
       
        initComponents();
        icon();
        
        // border radius of frame
        setShape(new RoundRectangle2D.Double(0,0,getWidth(),getHeight(),15,15));
   
    }
     public void icon(){
            
            setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("Untitled design (4).png")));  
     }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        btUserName = new javax.swing.JLabel();
        btPassword = new javax.swing.JLabel();
        passBox = new javax.swing.JPasswordField();
        usernameTxtbox = new javax.swing.JTextField();
        jCheckBox2 = new javax.swing.JCheckBox();
        btnCancel = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jToolBar1.setRollover(true);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(344, 501));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btUserName.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        btUserName.setForeground(new java.awt.Color(255, 255, 255));
        btUserName.setText("User Name");
        getContentPane().add(btUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, -1, -1));

        btPassword.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        btPassword.setForeground(new java.awt.Color(255, 255, 255));
        btPassword.setText("Password");
        getContentPane().add(btPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 320, -1, -1));

        passBox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        passBox.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        passBox.setBorder(null);
        getContentPane().add(passBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, 200, 30));

        usernameTxtbox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        usernameTxtbox.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        usernameTxtbox.setBorder(null);
        usernameTxtbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameTxtboxActionPerformed(evt);
            }
        });
        getContentPane().add(usernameTxtbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, 200, 30));

        jCheckBox2.setContentAreaFilled(false);
        jCheckBox2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 370, 20, 20));

        btnCancel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(102, 0, 255));
        btnCancel.setText("Cancel");
        btnCancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelMouseClicked(evt);
            }
        });
        getContentPane().add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 430, 50, 20));

        btnLogin.setBackground(new java.awt.Color(0, 102, 255));
        btnLogin.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setText("Login");
        btnLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 400, 120, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\pplch\\Downloads\\vega mobile.png")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 500));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void usernameTxtboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameTxtboxActionPerformed
   // TODO add your handling code here:
    }//GEN-LAST:event_usernameTxtboxActionPerformed

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        if (jCheckBox2.isSelected()){

            passBox.setEchoChar((char)0);

        } else {

            passBox.setEchoChar('•');
        }
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void btnCancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelMouseClicked
          ExitBox exb = new ExitBox();
            exb.setVisible(true);
    }//GEN-LAST:event_btnCancelMouseClicked

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
             String usernameVr = usernameTxtbox.getText();

             String passwordVr = passBox.getText();

        try {

            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/eterprise_db" , "root" , "");

            PreparedStatement stp = (PreparedStatement) con . prepareStatement("Select username, password from login where username=? and password=?");

            stp.setString (1 , usernameVr);
            stp.setString (2 , passwordVr);

            ResultSet  rs = stp . executeQuery ();

            if (rs.next()) {

                dialogBox dbox = new dialogBox();
                dbox.setVisible(true);
                dispose();

            } else {

                dialogBox2 dbox2 = new dialogBox2();
                dbox2.setVisible(true);
                dispose();

                //clearing wrong input
                usernameTxtbox. setText("");
                passBox. setText("");
            }
        }

        catch (SQLException sqlException) {
        }       
    }//GEN-LAST:event_btnLoginActionPerformed

    
    public static void main(String args[]) {
    
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new loginPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btPassword;
    private javax.swing.JLabel btUserName;
    private javax.swing.JLabel btnCancel;
    private javax.swing.JButton btnLogin;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JPasswordField passBox;
    private javax.swing.JTextField usernameTxtbox;
    // End of variables declaration//GEN-END:variables
}
